# Generated by Django 3.1.6 on 2021-02-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Категория', max_length=50, unique=True)),
                ('category_description', models.TextField(blank=True, help_text='Описание категории', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(help_text='Единица измерения', max_length=50, unique=True)),
                ('short_measure_name', models.CharField(blank=True, default=models.CharField(help_text='Единица измерения', max_length=50, unique=True), help_text='Короткое наименование единицы измерения', max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Продукт', max_length=50, unique=True)),
                ('product_value', models.IntegerField()),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('product_measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.measure')),
            ],
        ),
    ]
